# Generated by Django 4.2.6 on 2023-11-02 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crud_medicos', '0001_initial'),
        ('crud_pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateTimeField()),
                ('Descricao', models.TextField()),
                ('Status', models.CharField(choices=[('A Confirmar', 'A Confirmar'), ('Confirmado', 'Confirmado'), ('Finalizado', 'Finalizado')], max_length=20)),
                ('Medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_medicos.doctor')),
                ('Paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_pacientes.patient')),
            ],
        ),
    ]
