# Generated by Django 4.2.6 on 2023-11-01 00:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=255)),
                ('Endereco', models.CharField(max_length=255)),
                ('Numero', models.CharField(max_length=10)),
                ('Cidade', models.CharField(max_length=100)),
                ('UF', models.CharField(max_length=2)),
                ('Pais', models.CharField(max_length=100)),
                ('Telefone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Telefone must be in the format '(##) #####-####' or '(##) ####-####'", regex='^\\(\\d{2}\\) \\d{1}\\d{4}-\\d{4}$|^\\(\\d{2}\\) \\d{4}-\\d{4}$')])),
                ('CEP', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="CEP must be in the format '#####-###'", regex='^\\d{5}-\\d{3}$')])),
                ('Data_Criacao', models.DateTimeField()),
            ],
        ),
    ]
